name: Trigger BVT In Other Repp

on:
  workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  Trigger_BVT:

    name: "Trigger BVT"
    env:
      GITHUB_ORG: lexisnexis-iac
      GITHUB_REPO: hpccplat-azure-automation-dev
      GITHUB_REPO_BRANCH: main
      WF_YAML_FILE: repo-dispatch-apply.yaml

    runs-on: Ubuntu-22.04
    steps:
    - name: 'Call Curl to trigger another workflow'
      run: |
        hpcc_version=9.10.4
        data="{\"ref\":\"main\", \"inputs\": { \"hpcc_version\":\"$hpcc_version\" }}"

        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GODJI_GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GITHUB_ORG/$GITHUB_REPO/actions/workflows/$WF_YAML_FILE/dispatches \
          -d "${data}"
